spring:
  application:
    name: AuthService

  mail:
    host: smtp.gmail.com
    port: 587
    username: devshadow17@gmail.com
    password: lprd qqfy vwza mxvq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mongodb:
    uri: mongodb://localhost:27017/auth-service-hisab

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

imagekit:
  publicKey: "public_syZvipOdEw/EI5EM1AxwHEp92tc="
  privateKey: "private_JzgDsc1aNkSTbLiI9mvL905u+NQ="
  urlEndpoint: "https://ik.imagekit.io/cf7owq7yn/"